version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: data
#    ports:
#      - "5431:5432"

  redis:
    image: redis:latest
    depends_on:
      - db
#    ports:
#      - "6379:6379"
  celery:
    build: .
    command: celery -A app.celery_app worker -c 2
    depends_on:
      - redis

  app:
    build: .
    ports:
      - "5000:5000"
    command: python3 app.py
    depends_on:
      - celery
